---
version: "2"

services:
  openldap:
    image: osixia/openldap
    ports:
      - 389:389
      - 636:636
    env_file: ./ldap.env
    healthcheck:
      test: "[ -e /run/slapd/slapd.pid ] || exit 1"
      interval: 30s
      timeout: 30s
      retries: 100
    volumes:
      - ./ldap/certs:/container/service/slapd/assets/certs
      # - ./seeders:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - type: bind
        source: /dev/urandom
        target: /dev/urandom
        read_only: true

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

      - type: bind
        source: ./ldifs
        target: /container/service/slapd/assets/config/bootstrap/ldif/custom
        read_only: true

    command: "--copy-service --loglevel debug"
    networks:
      - lab

  ldap_admin:
    image: wheelybird/ldap-user-manager
    environment:
      - LDAP_IGNORE_CERT_ERRORS=true
      - LDAP_URI=ldaps://openldap:636
      - LDAP_REQUIRE_STARTTLS=TRUE
      - LDAP_BASE_DN=dc=acme,dc=org
      - LDAP_ADMIN_BIND_DN=cn=admin,dc=acme,dc=org
      - LDAP_ADMIN_BIND_PWD=admin
      - LDAP_USER_OU=users
      - LDAP_ADMINS_GROUP=admin
    ports:
      - 3000:443
    networks:
      - lab

  ssh-container:
    build:
      dockerfile: Dockerfile
      context: ./ssh-container
    depends_on:
      openldap:
        condition: service_healthy
    ports:
      - "2222:22"
    networks:
      - lab
  openvpn:
    build:
      context: ./openvpn-config
    depends_on:
      - openldap
    volumes:
      - ./openvpn-config/logs/:/var/log/openvpn
    env_file: ./openvpn.env
    ports:
      - 1194:1194/udp
    cap_add:
      - "NET_ADMIN"
    environment:
      - DEBUG=1
    networks:
      - lab
  apache-server:
    depends_on:
      openldap:
        condition: service_healthy
    build:
      context: ./apache-config
      dockerfile: Dockerfile
    env_file: ./apache.env
    ports:
      - 5200:80
    networks:
      - lab

  dns-server:
    build:
      dockerfile: Dockerfile
      context: ./dns-server
    networks:
      - lab
    restart: always

  kerberos:
    image: chistousov/kerberos5:1.0.0
    env_file: ./kerberos.env
    ports:
      - 750:750
      - 750:750/udp
    mem_limit: 512M
    volumes:
      - type: bind
        source: /dev/urandom
        target: /dev/urandom
        read_only: true

      - type: bind
        source: /etc/timezone
        target: /etc/timezone
        read_only: true

      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true

      # - type: volume
      #   source: kdc-volume
      #   target: /etc/krb5kdc

    restart: unless-stopped
    healthcheck:
      test: "[ -e /krb5kdc.pid ] || exit 1"
      interval: 30s
      timeout: 30s
      retries: 100
    labels:
      - docker-volume-backup.stop-during-backup=kdc-database-backup-db-stop-label
    depends_on:
      openldap:
        condition: service_healthy

    networks:
      - lab

networks:
  lab:
    external: true
    name: lab

volumes:
  kdc-volume:
